"""Altera_coluna_dados_preenchidos_para_JSON

Revision ID: 185bbbd93fb4
Revises: 336bf9147401
Create Date: 2025-11-06 13:48:26.478711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185bbbd93fb4'
down_revision = '336bf9147401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Anexo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__Anexo__protocolo__534D60F1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Protocolo', ['protocolo_id'], ['id'])

    with op.batch_alter_table('CampoModelo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__CampoMode__model__4316F928'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ProtocoloModelo', ['modelo_id'], ['id'])

    with op.batch_alter_table('Historico', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__Historico__proto__4F7CD00D'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Protocolo', ['protocolo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Historico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK__Historico__proto__4F7CD00D'), 'Protocolo', ['protocolo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('CampoModelo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK__CampoMode__model__4316F928'), 'ProtocoloModelo', ['modelo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Anexo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK__Anexo__protocolo__534D60F1'), 'Protocolo', ['protocolo_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
