"""Adiciona flag habilita_conferencia ao modelo

Revision ID: 4297a21cba88
Revises: 185bbbd93fb4
Create Date: 2025-11-20 15:10:50.903505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4297a21cba88'
down_revision = '185bbbd93fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProtocoloModelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilita_conferencia', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProtocoloModelo', schema=None) as batch_op:
        batch_op.drop_column('habilita_conferencia')

    # ### end Alembic commands ###
