"""Adiciona direcionamento de protocolo para colaborador

Revision ID: 576c2aa20202
Revises: d8c77284c0a3
Create Date: 2025-09-24 18:00:00.000000 # A data será diferente para você

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576c2aa20202'
down_revision = 'd8c77284c0a3' # Verifique se a revisão anterior está correta
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    with op.batch_alter_table('Protocolo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colaborador_destinatario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_protocolo_colaborador_destinatario', # Nome da constraint
            'Colaborador', 
            ['colaborador_destinatario_id'], 
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    with op.batch_alter_table('Protocolo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_protocolo_colaborador_destinatario', type_='foreignkey')
        batch_op.drop_column('colaborador_destinatario_id')
    # ### end Alembic commands ###