"""Adiciona data_vencimento ao Protocolo

Revision ID: 70a49fa0c952
Revises: 576c2aa20202
Create Date: 2025-09-25 09:50:00.000000 # A data será diferente para você

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a49fa0c952'
down_revision = '576c2aa20202' # Verifique se o 'revises' original está aqui
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    with op.batch_alter_table('Protocolo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_vencimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    with op.batch_alter_table('Protocolo', schema=None) as batch_op:
        batch_op.drop_column('data_vencimento')

    # ### end Alembic commands ###