"""Criaçao inicial das tabelas via modelos

Revision ID: 74e18b9a1384
Revises: 
Create Date: 2025-09-24 13:51:01.184614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '74e18b9a1384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Setor')
    op.drop_table('Colaborador')
    op.drop_table('Protocolo')
    op.drop_table('Historico')
    op.drop_table('ProtocoloModelo')
    op.drop_table('CampoModelo')
    op.drop_table('Anexo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Anexo',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome_arquivo', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('caminho_arquivo', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('protocolo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['protocolo_id'], ['Protocolo.id'], name=op.f('FK__Anexo__protocolo__534D60F1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Anexo__3213E83F4FA84305'))
    )
    op.create_table('CampoModelo',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome_campo', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('tipo_campo', sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('opcoes', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('obrigatorio', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('modelo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['ProtocoloModelo.id'], name=op.f('FK__CampoMode__model__4316F928'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__CampoMod__3213E83FE3AD4DA1'))
    )
    op.create_table('ProtocoloModelo',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=150, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('setor_proprietario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['setor_proprietario_id'], ['Setor.id'], name='FK__Protocolo__setor__3E52440B'),
    sa.PrimaryKeyConstraint('id', name='PK__Protocol__3213E83FF1A05122')
    )
    op.create_table('Historico',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_ocorrencia', mssql.DATETIME2(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('protocolo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('colaborador_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['Colaborador.id'], name=op.f('FK__Historico__colab__5070F446')),
    sa.ForeignKeyConstraint(['protocolo_id'], ['Protocolo.id'], name=op.f('FK__Historico__proto__4F7CD00D'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Historic__3213E83FAB31BBAF'))
    )
    op.create_table('Protocolo',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('numero_protocolo', sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('assunto', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('data_criacao', mssql.DATETIME2(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('status', sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'), server_default=sa.text("('Aberto')"), autoincrement=False, nullable=False),
    sa.Column('criado_por_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('setor_destinatario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modelo_usado_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dados_preenchidos', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['Colaborador.id'], name=op.f('FK__Protocolo__criad__49C3F6B7')),
    sa.ForeignKeyConstraint(['modelo_usado_id'], ['ProtocoloModelo.id'], name=op.f('FK__Protocolo__model__4BAC3F29')),
    sa.ForeignKeyConstraint(['setor_destinatario_id'], ['Setor.id'], name=op.f('FK__Protocolo__setor__4AB81AF0')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Protocol__3213E83F732ED4F8'))
    )
    op.create_table('Colaborador',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.NVARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('senha_hash', sa.NVARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('role', sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('setor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['Setor.id'], name=op.f('FK__Colaborad__setor__3B75D760')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Colabora__3213E83F5AC6E582'))
    )
    op.create_table('Setor',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Setor__3213E83F099CEC21'))
    )
    # ### end Alembic commands ###
