"""Adiciona tabela Fornecedor e relacao com Protocolo

Revision ID: 90379530623a
Revises: 70a49fa0c952
Create Date: 2025-09-25 10:20:00.000000 # A data será diferente para você

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90379530623a'
down_revision = '70a49fa0c952' # Verifique se o 'revises' original está aqui
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    # 1. Cria a nova tabela Fornecedor
    op.create_table('Fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('contato_nome', sa.String(length=100), nullable=True),
    sa.Column('contato_email', sa.String(length=120), nullable=True),
    sa.Column('contato_telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('razao_social')
    )
    
    # 2. Altera a tabela Protocolo para adicionar as novas colunas
    with op.batch_alter_table('Protocolo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_externo', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('fornecedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_protocolo_fornecedor', 'Fornecedor', ['fornecedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    with op.batch_alter_table('Protocolo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_protocolo_fornecedor', type_='foreignkey')
        batch_op.drop_column('fornecedor_id')
        batch_op.drop_column('is_externo')

    op.drop_table('Fornecedor')
    # ### end Alembic commands ###