"""Implementa sistema de Perfis e Permissoes (RBAC)

Revision ID: b6cd452bd36b
Revises: 6ededff4af26
Create Date: 2025-09-25 14:00:00.000000 # Sua data será diferente

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cd452bd36b'
down_revision = '6ededff4af26' # Verifique se a revisão anterior está correta
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    op.create_table('Permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('Perfil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('perfil_permissoes',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permissao_id'], ['Permissao.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['Perfil.id'], ),
    sa.PrimaryKeyConstraint('perfil_id', 'permissao_id')
    )
    with op.batch_alter_table('Colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_colaborador_perfil', 'Perfil', ['perfil_id'], ['id'])
        
        # Primeiro, removemos a constraint que depende da coluna 'role'
        # O nome da constraint pode variar, mas geralmente o Alembic o encontra.
        # Se este nome exato falhar, teremos que encontrá-lo no DBeaver.
        try:
            batch_op.drop_constraint('CK__Colaborado__role__3A81B327', type_='check')
        except Exception:
            print("Não foi possível encontrar a constraint de check pelo nome padrão, talvez já tenha sido removida.")
            pass # Continua mesmo se não encontrar a constraint

        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    with op.batch_alter_table('Colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'operador'"), nullable=False))
        batch_op.drop_constraint('fk_colaborador_perfil', type_='foreignkey')
        batch_op.drop_column('perfil_id')

    op.drop_table('perfil_permissoes')
    op.drop_table('Perfil')
    op.drop_table('Permissao')
    # ### end Alembic commands ###