"""Adiciona campo descricao ao Protocolo

Revision ID: d8c77284c0a3
Revises: 74e18b9a1384
Create Date: 2025-09-24 14:25:00.000000  # A data será diferente para você

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c77284c0a3'
down_revision = '74e18b9a1384' # Verifique se o 'revises' original está aqui
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    # Mantemos apenas a parte que adiciona a coluna 'descricao' à tabela 'Protocolo'
    with op.batch_alter_table('Protocolo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=False))

    # A parte que tentava alterar a tabela 'Historico' foi removida.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - CORRIGIDO ###
    # Mantemos apenas a parte que remove a coluna 'descricao' da tabela 'Protocolo'
    with op.batch_alter_table('Protocolo', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # A parte que tentava alterar a tabela 'Historico' foi removida.
    # ### end Alembic commands ###